---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy templated HTML files
  ansible.builtin.template:
    src: my_template.html.j2
    dest: /var/www/html/index.html
  notify: Restart Nginx

- name: Ensure Nginx is enabled and started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow HTTP traffic through the firewall
  ansible.builtin.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Enable UFW
  ansible.builtin.ufw:
    state: enabled
